export default {
  homeDom: document.querySelector('.home-link'),
  logoDom: document.querySelector('.logo__link'),
  libraryDom: document.querySelector('.library-link'),
  filmLibraryPageSection: document.querySelector('.myFilmLibraryPage__section'),
  homePageSection: document.querySelector('.homePage'),
  filmDetailPageSection: document.querySelector('.film-details-page'),
  buttonShowLIstQueue: document.querySelector('.library__btn--queue'),
  buttonFilmsWatched: document.querySelector('.library__btn--watch'),
  buttonAddFilmToQueue: document.querySelector('.js-btn-queue'),
  buttonAddFilmToWatched: document.querySelector('.js-btn-watched'),
  buttonPrev: document.querySelector('.js-btn-prev'),
  buttonNext: document.querySelector('.js-btn-next'),
  homepageList: document.querySelector('.js-list-render'),
  searchFormDom: document.querySelector('.search__form'),
  inputFormDom: document.querySelector('.search__film'),
  searchFormErrorDom: document.querySelector('.search-form__error'),
  homePageBtn: document.querySelector('.homePage__btns'),
};
